# Regularly updates the CI container
name: Megatron Tag Bump Bot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-weekly-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge main back to weekly-bump
        run: |
          git fetch --unshallow
          git checkout weekly-bump
          git pull
          git merge --no-ff main -m "chore: Auto-merge main back to dev"
          git push

  mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_yamlfile.yml@v0.21.5
    needs: [update-weekly-branch]
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      yaml-path: '."vcs-dependencies"."megatron-lm".ref'
      file: requirements/manifest.json
      base-branch: weekly-bump
      cicd-labels: Run CICD,no-fail-fast
      pr-reviewers: "chtruong814"
    secrets:
      PAT: ${{ secrets.PAT }}
